cargo-features = ["codegen-backend"]

[package]
name = "zeta-lang"
version = "0.2.0-alpha"
edition = "2024"

[profile.release]
opt-level = 3
debug = "line-tables-only"
strip = "debuginfo"
lto = "thin"
codegen-units = 1

[profile.debug]
codegen-backend = "cranelift"

[build]
jobs = 12
rustflags = ["-Zthreads=8"]

[workspace]
members = [
    "ir",
    "scribe-parser",
    "emberforge-compiler",
    "codex-dependency-graph",
    "sentinel-typechecker",
    "engraver-assembly-emit",
    "zeta_utilities",
    "iris-math",
    "zeta-lsp",
    "zeta-compiler-api",
    "zetaup"
]

[dependencies]
mimalloc = "0.1.52"
zeta-compiler-api = { path = "./zeta-compiler-api" }
walkdir = "2.5.0"
thiserror = "2.0.17"
clap = { version = "4.5.53", features = ["derive"] }
