[package]
name = "zeta-compiler-api"
version = "0.2.0-alpha"
edition = "2024"

[dependencies]
scribe-parser = { path = "../scribe-parser" }
emberforge-compiler = { path = "../emberforge-compiler" }
codex-dependency-graph = { path = "../codex-dependency-graph" }
zetaruntime = { path = "../zeta_utilities" }
engraver-assembly-emit = { path = "../engraver-assembly-emit" }
ir = { path = "../ir" }
sentinel-typechecker = { path = "../sentinel-typechecker" }
walkdir = "2.5.0"

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = "0.7"

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_Threading",
] }
