[package]
name = "zeta_compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
cranelift = "0.102"
cranelift-module = "0.102"
cranelift-jit = "0.102"
cranelift-frontend = "0.102"
target-lexicon = "0.12"
pest = "2.8.0"
pest_derive = "2.8.0"
lazy_static = "1.5.0"
anyhow = "1.0.98"