[package]
name = "virtual_machine"
version = "0.1.0"
edition = "2024"

[dependencies]
#zeta_compiler = { path = "../zeta_compiler" }
#cranelift-codegen = "0.119.0"
#cranelift-frontend = "0.119.0"
#cranelift-module = "0.119.0"
#cranelift-simplejit = "0.68.0"
#target-lexicon = "0.13.2"

